### ISSUE TITLE
Move encoding/decoding logic to XS

### ISSUE THREAD

**Issue by TvdW** [TvdW/perl-DBD-Cassandra#13]
Let's face it, we can speed this up a lot by moving encoding and decoding to XS.

**Comment by TvdW** [comment]
Decoder is now done.

**Comment by djzort** [comment]
Im inserting 10_000 wide columns into a database, some 100_000 of them. It takes ages (hours in fact). Im doing so using 50x async'ing $sth's (if thats the correct terminology)

NYTProf shows that the encode is taking up all the time (see here)
![untitled](https://user-images.githubusercontent.com/937277/27813682-e7e255d6-60ba-11e7-9526-fdab881b6587.png)

I wonder if it would be helpful to use an orchish maneuver to cache the serialization? I'm pushing map types which on the surface wouldnt benefit but i could easily just use the same hashref over and over when the values are the same, which would allow for caching.

Just some thoughts as i wrestle with these things.

**Comment by TvdW** [comment]
If you're not using any of the following types, it may be worth giving the new-encoder branch a shot :

* date
* time
* decimal
* varint
* UDT

said branch: https://github.com/tvdw/perl-dbd-cassandra/tree/new-encoder

**Comment by TvdW** [comment]
@djzort Did you get a chance to test the new branch for performance?

**Comment by djzort** [comment]
The other two bugs were as the result of testing ;)

**Comment by TvdW** [comment]
Time to close this ticket. Afaict 0.13_007 contains all the fixes needed to ship the XS encoder. \o/

Giving cpantesters a few more days to break things, of course.

**Comment by djzort** [comment]
ive been using it, but honestly havent been able to measure a huge difference in performance.

**Comment by djzort** [comment]
thats not to say, in any way, that i dont appreciate your work in making it happen

**Comment by TvdW** [comment]
Hi Dean,

Curious, your flamegraph showed most time being spent in the encoder. If you have an updated flamegraph (please use Devel::StatProfiler, not NYTProf, which is known to be wildly inaccurate), please create a new issue and I'll be happy to have a look.

**Comment by djzort** [comment]
Ok thanks for the tip on Devel::StatProfiler. I will do some testing and see what the results are like.
