### ISSUE TITLE
How to insert a user-defined type

### ISSUE THREAD

**Issue by rmmax** [TvdW/perl-DBD-Cassandra#17]
Hello,
I have a user-defined type as 
```
CREATE TYPE address (
  street text,
  city text,
  zip_code int
);
```
and a table defined as 
```
create table person (
  person_id int PRIMARY KEY,    
  first_name text,
  last_name text,
  email text,
  mobile text,
  address_book map<text, frozen<address>>
);  
```
In my perl script, I got error message like
Cannot encode type 48. Sending a NULL instead, this is probably not what you want !
when I run 
```
$sth->prepare("INSERT INTO person (person_id, first_name, last_name, email, mobile, address_book) VALUES (?, ?, ?, ?, ?, ?)");
$sth->execute((453654, 'John', 'Lucy', 'JLucy@gmail', '33086567423', { "book_1" => { street => 'No, 34 cats road', city => 'main', zip_code => 23356}} ));
```
I can run however insert command in cql. Dose DBD::Cassandra support user-defined type?

**Comment by TvdW** [comment]
Fixed with https://github.com/TvdW/perl-DBD-Cassandra/commit/c0d34e16651dab1d0ff399e4edce0f28039b41bb
