### ISSUE TITLE
Numbers and placeholders

### ISSUE THREAD

**Issue by djzort** [TvdW/perl-DBD-Cassandra#19]
When a column type is text and i provide a number to the place holder, DBD::Cassandra doesnt coerce it properly to a string by quoting it. For example...

```
my $sth = $dbh->prepare(q/ INSERT INTO foobar (id,text_field) VALUES (?,?) /);
$sth->execute(1,5678);
```

Gives an **Invalid map literal** error.

If i quote the number, i still get the same error.
`$sth->execute(1,'5678');`

So I am guessing it's DBD guessing at what to do rather than looking deep into what perl thinks the variable is.

The solution for me so far, is to quote the placeholder.

```
my $sth = $dbh->prepare(q/ INSERT INTO foobar (id,text_field) VALUES (?,'?') /);
$sth->execute(1,5678);
```

**Comment by TvdW** [comment]
Hi Dean,

What does your table definition look like, so I can try to reproduce this?

[edit] guessed `create table foobar (id int primary key, text_field text);`, but can't reproduce.

Also, which Cassandra version do you run?

**Comment by djzort** [comment]
It looks like:
```
CREATE TABLE dev.biglist (
prodcode varchar PRIMARY KEY,
pc_au_0001 map<text,text>,
pc_au_0002 map<text,text>,
pc_au_0003 map<text,text>,
pc_au_0004 map<text,text>,
pc_au_0005 map<text,text>,
pc_au_0006 map<text,text>,
pc_au_0007 map<text,text>,
pc_au_0008 map<text,text>,
..
pc_nz_0001 map<text,text>,
pc_nz_0002 map<text,text>,
pc_nz_0003 map<text,text>,
pc_nz_0004 map<text,text>,
pc_nz_0005 map<text,text>,
pc_nz_0006 map<text,text>,
pc_nz_0007 map<text,text>,
pc_nz_0008 map<text,text>,

```

but goes all the way from 0001 through to 9999 for both au (Australia) and nz (New Zealand)

**Comment by djzort** [comment]
Basically, its storing availability data about products for each postcode in NZ and AU. We can just look up by prodcode and pluck out the postcode we are concerned with at that time.

**Comment by djzort** [comment]
My insert looks like:
`my $sth = $dbh->prepare(q/ INSERT INTO biglist (prodcode, pc_au_0001, ...) VALUES ( ?, { days : ? }, .. ) /);`

But with 20,000 columns worth of data.

**Comment by TvdW** [comment]
Is this the error you're seeing?

```
cqlsh:dbd_cassandra_tests> create table test (id int primary key, field map<text,text>);
cqlsh:dbd_cassandra_tests> insert into test (id, field) values (5, { days: '2015' });
InvalidRequest: code=2200 [Invalid query] message="Invalid user type literal for ColumnDefinition{name=field, type=org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type), kind=REGULAR, componentIndex=0, indexName=null, indexType=null} of type map<text, text>"
```

If so, try quoting the literal in the query, 'days'.

**Comment by djzort** [comment]
To make things fun, I am running against:
`ScyllaDB 1.7.0`

RIght now i am just running it inside their Docker image from Docker Hub. So its s snap to set up

**Comment by TvdW** [comment]
As an aside, please note that you can insert maps straight from DBD::Cassandra :

```
my $sth= $dbh->prepare('insert into table (id, something) values (?, ?)');
$sth->execute(1, { days => 5 });
```

**Comment by djzort** [comment]
^^^^ ok wow that fills me with great great joy. Please mention it in the pod!


This is the prepare right now thats working ok:
```
# for every product
my $insertcql = sprintf('INSERT INTO biglist ( prodcode, %s ) VALUES ( ?, %s )',
        join(', ', map { lc("pc_$_") } @postcodes),
        join(', ', map { q/{ 'days' : '?' }/ } @postcodes)
);
```

Without _days_ having single quotes, I get the error:

`DBD::Cassandra::st x_finish_async failed: Error 8704: Invalid user type literal for pc_au_0002 of type map<text, text> at everyproduct.pl line 244.`

Without the _?_ having single quotes, i get the error:

`DBD::Cassandra::st x_finish_async failed: Error 8704: Invalid map literal for pc_au_0002: bind variables are not supported inside collection literals at everyproduct.pl line 244.`

**Comment by TvdW** [comment]
I recommend against quoting the ?, it will just result in you inserting a lot of question marks into the database.

As for the second error which occurs when not quoting the ?, I think the error is clear: `bind variables are not supported inside collection literals`. ScyllaDB does not seem to support those queries, it's not a driver side bug.

I recommend inserting the maps as shown in my previous example, which will solve your problem.

As for the pod: https://github.com/TvdW/perl-DBD-Cassandra/commit/d32e67a904bf6fafa7e3e817dd4869451a65ff50

Considering this issue closed now.

**Comment by djzort** [comment]
Ok thanks i really appreciate your time and effort. placing a hash in execute is excellent.
