### ISSUE TITLE
Decimal type

### ISSUE THREAD

**Issue by sugar84** [TvdW/perl-DBD-Cassandra#2]
Hi!
Cassandra is great, this module is great!
How about to add support of decimal type? Is it planned?

**Comment by TvdW** [comment]
I add things when I need them or people request them (or when I have nothing better to do). Now that this ticket is here, I will start working on it.

**Comment by sugar84** [comment]
Nice. Thank you.

**Comment by ccakes** [comment]
Have you made a start on this or have any thoughts on how you wanted to implement this? I'm just trying this module out on some data using the decimal type.

I don't need the precision (not the original DBA) so I've hacked something up in the interim but if you haven't started yet I'd be happy to have a run at implementing this properly.

**Comment by TvdW** [comment]
Fixed in e7ec7da81014f064884a9749658018080e151b1c. The implementation is naive, but it'll get you your numbers
