### ISSUE TITLE
Pod Tests failing

### ISSUE THREAD

**Issue by djzort** [TvdW/perl-DBD-Cassandra#20]
For various reasons, I am running DBD::Cassandra on centos/rhel 6 with Test::Pod 1.4

_cpanm DBD::Cassandra_ fails because the Test::Pod tests fail

Once i cpanm Test::Pod (which takes Test::Pod to 1.51) the tests pass

I think you just need to manually set a minimum for Test::Pod in the dist.ini (although youre using autorepreq, so i didnt want to send a PR)

**Comment by TvdW** [comment]
Test::Pod is only used in the author tests, and won't be run unless you have the AUTHOR_TESTING environment variable set.

I don't consider this a bug, these tests aren't meant to be run upon installation and dependencies for those tests should therefore not be required.
