### ISSUE TITLE
Request: clone() function on $sth

### ISSUE THREAD

**Issue by djzort** [TvdW/perl-DBD-Cassandra#21]
When doing async inserts (as described in the pod), generating the prepared queries for large inserts (in my case 10_000 columns worth) takes quite a while and then is 10-50x more to create the handler for each parallel insert.

Would it be possible to implement a clone() function, which would be able to reused the generated serializers etc. This would make generating handlers way way faster and save hugely on memory (not having to have 10-50x copies of the same generated anonymous sub)

**Comment by TvdW** [comment]
DBI wouldn't support this, so no, sadly not.

That said, all the preparation work is cached, the subs are only created once, the only significant overhead comes from DBI's statement creation.

If you want high performance, have a look at using Cassandra::Client directly.
