### ISSUE TITLE
selectall_arrayref problem

### ISSUE THREAD

**Issue by djzort** [TvdW/perl-DBD-Cassandra#22]
it seems that when only 1 result is returned, selectall_arrayref returns a single hashref, rather than an arrayref with a single hashref therein.

**Comment by TvdW** [comment]
Do you have a reproducible test case? I don't see how this is possible, the DBI API doesn't allow for that

[edit] Maybe a DBI bug? :)

**Comment by djzort** [comment]
youre completely right, its a mistake at my end between they keyboard and my seat. sorry to waste your attention
