### ISSUE TITLE
Question regarding placeholders

### ISSUE THREAD

**Issue by djzort** [TvdW/perl-DBD-Cassandra#23]
The postgres dbd is clever and converts \\@list into a list for IN queries. Does this module do the same?

ie
```
@ids = qw/ 123 456 789 /;
my $sth->prepare("SELECT something FROM somethings WHERE id IN (?)");
$sth->execute(\@ids);
```

**Comment by TvdW** [comment]
Yes, although in your example you are putting a list inside a single-item placeholder.

    SELECT something FROM somethings WHERE id IN ?

**Comment by djzort** [comment]
thank you, much appreciated. perhaps you might also note it in the pod?
