### ISSUE TITLE
Cassandra::Client - Can't call method "get_one_cb" on an undefined value 

### ISSUE THREAD

**Issue by sergle** [TvdW/perl-DBD-Cassandra#25]
When connection to Cassandra is lost, I often observe error:

`EV: error in callback (ignoring): Can't call method "get_one_cb" on an undefined value at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Cassandra/Client/NetworkStatus.pm line 61`

`61                     $self->{pool}->get_one_cb($next);`

Probably there should be  if ($self->{pool}) { ... } 

Cassandra::Client 0.13, Perl 5.22.1 on Ubuntu 16.04.3

**Comment by TvdW** [comment]
Fixed with d2dd99456875b4f539bf76ffbd6a3e78a7aa261d - Thanks for noticing
