### ISSUE TITLE
Expected behaviour with multiple servers

### ISSUE THREAD

**Issue by djzort** [TvdW/perl-DBD-Cassandra#29]
i am feeding a lot of data in to cassanda, to do so i am using the async option with 200 $sth's which are being recycled as they become available.

The connect string I am using features host=192.0.2.1,192.0.2.2,192.0.2.3,192.0.2.4 and consistency=any

My expected behaviour is that all four servers would be kept busy with the inserts, however it seems that only the first server is doing any work (based on cpu load)

I would also mention that the pod example suggests a host=$hostname, then the bullet list offers hostname and hosts which i assume are synonyms? This isnt clear though

**Comment by TvdW** [comment]
Heya,

DBD::Cassandra will use the 'host' argument (or hosts, or hostname, don't remember the exact name) to *seed* a pool of connections. It's going to shuffle the list you give it, then connect to each of them until there's a connection, and then use all nodes in the local datacenter to route queries. By default though, it will only use two connections, as a single Perl interpreter won't keep Cassandra busy enough to warrant using more.

If you do have multiple Perl interpreters running queries, the load will be distributed properly. If you have a single Perl interpreter running queries, the load will be distributed over two hosts, but Perl will max out its own capabilities before that's a problem.

However, based on your description of what you're seeing, it sounds like you have a hot partition. I would recommend checking 'nodetool tpstats' and looking at the rate of 'completed' tasks in the native transport requests pool (grab the number, wait 10 seconds, do it again, subtract). That's the amount of queries executed on each server. Then, compare it with the rate of 'mutation' tasks, which indicates the number of writes that actually hit the disk. Ideally these would grow at roughly the same rate (minus a constant factor), but with a data imbalance I would expect the native requests to increase evenly across all nodes, while the mutation counter mainly increases on a single node.

**Comment by djzort** [comment]
ok so host, hosts, and hostname are synonyms. thats good, as i was worried maybe i host would ignore server 2,3,4 - although "worry" is s stretch as its not hugely difficult to adjust the connect string.

in this particular use case in just loading lots of data with a single script. ive settled on 300 $sth's as going beyond that seems to jam things up - even though cpu usage isnt high. in fact with just 300 perl is using perhaps 10% cpu and two of the cassanda (scylla) servers is sitting on 20% on two cores (dual core azure instances in this case) and iotop isnt showing any significant write activity.

there are reasonable waits as the loop hits a blocking $sth, and then a jump of activity as it cycles through available $sth's that have become available... 

so its interesting that you mention that DBD::Cassandra will only make use of two connections, as that is what im seeing, but curious that perl doesnt seem to be working the servers that hard.

perhaps should use EV or something so that it can pick off the $sth's as soon as each one becomes available, rather than being blocked and then surging through a group of clear handlers?

**Comment by TvdW** [comment]
You could use Cassandra::Client (library underneath DBD::Cassandra) which gives you direct eventloop integration via AnyEvent. It could also be that you’re blocked by a configuration detail in the defaults that would mostly impact high latency (>5ms) connections. The easiest way to work around that is to create multiple client objects and use them all, although that’s arguably a bug in my code. 

In any case, best performance will come from running your writer script in parallel: even if you use many client objects, you can only speed up 10x from what you have now (considering it’s at 10% cpu)

**Comment by djzort** [comment]
Thanks @TvdW - what sort of ratio of $sth's per $dbh would you recommend?

**Comment by djzort** [comment]
Ok after a week or so of experimenting (fiddling?) it seems that bulk data inserts are by many magnitues faster if performed wrapped in 'BEGIN UNLOGGED BATCH' and 'END BATCH', with the real magic to ensure that data with the same 'partition key' should all be in the same batch.

Relaxing the compaction thresholds a little also seems to help, ie 
{'class' : 'SizeTieredCompactionStrategy', 'min_threshold' : 32, 'max_threshold' : 1024 }

On the other hand, scattering single inserts across a number of $dbh and $sth is catastrophic for insert performance.

Im not sure if this is something that people with actual Cassandra experience know about, but from the DBI perl user coming at Cassandra for the first time - this is all interesting and new

**Comment by TvdW** [comment]
Late reply, sorry, medical stuff :)

> what sort of ratio of $sth's per $dbh would you recommend?

idk, I will always go straight to Cassandra::Client for bulk writes. much faster and less complex because there are no sth's to juggle. 

> Im not sure if this is something that people with actual Cassandra experience know about, but from the DBI perl user coming at Cassandra for the first time - this is all interesting and new

Yeah, I'm sure there's a bit of a learning curve... unlogged batches can indeed speed up writes significantly, when done right, as some computations can be removed. But more importantly, it bypasses a lot of the DBI complexity around handling individual queries, so the amount of rows that Perl itself can push every second goes up tremendously as well.

Good luck on your journey 😃
