### ISSUE TITLE
bigendian-littleendian issue with double type

### ISSUE THREAD

**Issue by gyathaar** [TvdW/perl-DBD-Cassandra#5]
in Cassandra/Type.pm
there are the following lines:

sub p2c_double { return   _pack('d', 8, undef, @_) }
sub c2p_double { return _unpack('d', 8, undef, @_) }

this causes double values to be stored incorrectly in the database (atleast for cassandra 3.3, havent tested in other versions)
(It may apply to float values also.. havent tested)

the correct code should be
sub p2c_double { return   _pack('d>', 8, undef, @_) }
sub c2p_double { return _unpack('d>', 8, undef, @_) }

for example
123.4 ends up getting stored as -1.54234871456036e-180 in the database ...
if you read the value with the DBD::Cassandra you will however get the correct value out again due to the same incorrect conversion there
My issue is I used perl to store values into database and java for reading the values out again...

I solved my problem for now by doing:
my $newval = unpack('d' , pack('d>', $val));
and storing newval instead...

I see one issue though with fixing the bug... people that have been using the bugged code for storing and reading values from database would start getting wrong values for values previously stored in database... you you might need to create some kind of compatibility modus...

**Comment by TvdW** [comment]
Ouch! That's a painful bug.

I am going to push an updated version right away and have an entry in the changelog, warning about this, plus an entry in the POD.
